// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSl7I6ZL-klhw_l5xdPE1-UD4X9smfZ00',
    appId: '1:153729009207:web:e0d0517727829a507561b2',
    messagingSenderId: '153729009207',
    projectId: 'project-1-7de88',
    authDomain: 'project-1-7de88.firebaseapp.com',
    storageBucket: 'project-1-7de88.appspot.com',
    measurementId: 'G-4T7HPPEMT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuKBmObvooMW4zloXOWj2XUmsRPM94eO4',
    appId: '1:153729009207:android:18d5ccee83cd83b37561b2',
    messagingSenderId: '153729009207',
    projectId: 'project-1-7de88',
    storageBucket: 'project-1-7de88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenVR7-CwUDrhkl8fPNhenltBNQJHCZPc',
    appId: '1:153729009207:ios:51117c317e39745a7561b2',
    messagingSenderId: '153729009207',
    projectId: 'project-1-7de88',
    storageBucket: 'project-1-7de88.appspot.com',
    iosClientId: '153729009207-bt2fgpcpjqd129b13kfjhbnlr8m23k9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBenVR7-CwUDrhkl8fPNhenltBNQJHCZPc',
    appId: '1:153729009207:ios:19174ac083b5965c7561b2',
    messagingSenderId: '153729009207',
    projectId: 'project-1-7de88',
    storageBucket: 'project-1-7de88.appspot.com',
    iosClientId: '153729009207-jnnov8lgul7rkbs27odibsfpf3hq9lej.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientApp.RunnerTests',
  );
}
